// GENERATED by tools/build-resumes.py from ../Ideal Resumes. One PDF per target role.
export type Resume = { label: string; file: string; kb: number; group: string };
export const RESUMES: Resume[] = [
  { label: "AI Engineer", file: "Adarsh_Dwivedi_AI_Engineer.pdf", kb: 91, group: "AI and agents" },
  { label: "AI Product Engineer", file: "Adarsh_Dwivedi_AI_Product_Engineer.pdf", kb: 101, group: "AI and agents" },
  { label: "AI Product Manager", file: "Adarsh_Dwivedi_AI_Product_Manager.pdf", kb: 100, group: "Product and analytics" },
  { label: "Agentic AI Engineer", file: "Adarsh_Dwivedi_Agentic_AI_Engineer.pdf", kb: 99, group: "AI and agents" },
  { label: "Applied ML and Deep Learning Engineer", file: "Adarsh_Dwivedi_Applied_ML_and_Deep_Learning_Engineer.pdf", kb: 99, group: "Machine learning" },
  { label: "Business Analyst", file: "Adarsh_Dwivedi_Business_Analyst.pdf", kb: 94, group: "Product and analytics" },
  { label: "Data Analyst", file: "Adarsh_Dwivedi_Data_Analyst.pdf", kb: 95, group: "Product and analytics" },
  { label: "Data Scientist", file: "Adarsh_Dwivedi_Data_Scientist.pdf", kb: 91, group: "Machine learning" },
  { label: "Deep Learning Engineer", file: "Adarsh_Dwivedi_Deep_Learning_Engineer.pdf", kb: 97, group: "Machine learning" },
  { label: "DevOps and Platform Engineer", file: "Adarsh_Dwivedi_DevOps_and_Platform_Engineer.pdf", kb: 96, group: "Engineering" },
  { label: "Generative AI Engineer", file: "Adarsh_Dwivedi_Generative_AI_Engineer.pdf", kb: 97, group: "AI and agents" },
  { label: "Machine Learning Engineer", file: "Adarsh_Dwivedi_Machine_Learning_Engineer.pdf", kb: 100, group: "Machine learning" },
  { label: "Product Manager", file: "Adarsh_Dwivedi_Product_Manager.pdf", kb: 99, group: "Product and analytics" },
  { label: "Software Engineer", file: "Adarsh_Dwivedi_Software_Engineer.pdf", kb: 98, group: "Engineering" },
];
