// GENERATED by tools/build-resumes.py. One PDF per target role.
export type Resume = { label: string; file: string; kb: number };
export const RESUMES: Resume[] = [
  { label: "AI Engineer", file: "Adarsh_Dwivedi_AI_Engineer.pdf", kb: 91 },
  { label: "AI Product Engineer", file: "Adarsh_Dwivedi_AI_Product_Engineer.pdf", kb: 100 },
  { label: "AI Product Manager", file: "Adarsh_Dwivedi_AI_Product_Manager.pdf", kb: 99 },
  { label: "Agentic AI Engineer", file: "Adarsh_Dwivedi_Agentic_AI_Engineer.pdf", kb: 99 },
  { label: "Applied ML and Deep Learning Engineer", file: "Adarsh_Dwivedi_Applied_ML_and_Deep_Learning_Engineer.pdf", kb: 99 },
  { label: "Business Analyst", file: "Adarsh_Dwivedi_Business_Analyst.pdf", kb: 94 },
  { label: "Data Analyst", file: "Adarsh_Dwivedi_Data_Analyst.pdf", kb: 95 },
  { label: "Data Scientist", file: "Adarsh_Dwivedi_Data_Scientist.pdf", kb: 91 },
  { label: "Deep Learning Engineer", file: "Adarsh_Dwivedi_Deep_Learning_Engineer.pdf", kb: 97 },
  { label: "DevOps and Platform Engineer", file: "Adarsh_Dwivedi_DevOps_and_Platform_Engineer.pdf", kb: 97 },
  { label: "Generative AI Engineer", file: "Adarsh_Dwivedi_Generative_AI_Engineer.pdf", kb: 98 },
  { label: "Machine Learning Engineer", file: "Adarsh_Dwivedi_Machine_Learning_Engineer.pdf", kb: 100 },
  { label: "Product Manager", file: "Adarsh_Dwivedi_Product_Manager.pdf", kb: 99 },
  { label: "Software Engineer", file: "Adarsh_Dwivedi_Software_Engineer.pdf", kb: 98 },
];
