"""Generate src/content/projects.generated.ts from the resume system's profile.json.

One source of truth for every factual claim on this site and on the 14 resumes.
Change a number in profile.json, rebuild both, and they cannot disagree.
"""
import hashlib, json, pathlib, re

SRC = pathlib.Path(__file__).resolve().parents[2] / "resume-build" / "profile.json"
OUT = pathlib.Path(__file__).resolve().parents[1] / "src" / "content" / "projects.generated.ts"

# his "all the products under different domain heads"
DOMAINS = [
    ("public-interest", "Public-interest AI",
     "Problems that already have victims: crop loss, air quality, road capacity, floods and policing.",
     ["kadi", "krishimitra", "vayu", "margadrishti", "floodcast"]),
    ("health", "Clinical and diagnostic AI",
     "Medicine, where a wrong answer costs more than a click: grading, identification and clinical assistance built to abstain when unsure.",
     ["vaidyamitra", "medicure", "dr"]),
    ("trust", "Trust and verification",
     "Systems whose job is deciding whether to believe something, and showing the evidence for the answer.",
     ["agentiq", "orbweaver", "openforensics", "medguardx", "specledger", "artifact"]),
    ("agents", "Agents and AI infrastructure",
     "The plumbing under AI products: routing, caching, tool layers, retrieval and evaluation.",
     ["cachellm", "inflx", "travel", "orchestrate_sep", "evidence", "smartalloc"]),
    ("data", "Data and decision systems",
     "Turning a pile of records into a ranked queue somebody can actually work through.",
     ["creditsetu", "aircargo", "talent", "flipkart", "primetrademl", "costintel"]),
    ("systems", "Systems and foundations",
     "Lower-level work: algorithms, C++20, WebAssembly and on-chain risk.",
     ["graphsuite", "suiguard"]),
]

# richest narrative variant first; the rest are merged in for extra detail
PREF = ["product", "aiproduct", "swe", "agentic", "genai", "ai", "ml", "dl", "data", "ops", "aipe"]

def shots_version() -> str:
    """One hash over every shot. Next caps image patterns at 25, too few for a
    pattern per project, so all shots share a version and any change bumps it."""
    h = hashlib.sha1()
    for f in sorted((pathlib.Path(__file__).resolve().parents[1] / "public" / "shots").glob("*.jpg")):
        h.update(f.name.encode()); h.update(f.read_bytes())
    return h.hexdigest()[:8]


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")

def main() -> None:
    version = shots_version()
    P = json.loads(SRC.read_text())["projects"]
    placed = {s for _, _, _, slugs in DOMAINS for s in slugs}
    missing = [k for k in P if k not in placed]
    extra = [k for k in placed if k not in P]

    rows = []
    for did, dtitle, dblurb, slugs in DOMAINS:
        for slug in slugs:
            p = P.get(slug)
            if not p:
                continue
            bullets, seen = [], set()
            for v in PREF + sorted(p.get("bullets", {})):
                for b in p.get("bullets", {}).get(v, []):
                    key = b[:60]
                    if key not in seen:
                        seen.add(key)
                        bullets.append(b)
            st = p.get("stack")
            if isinstance(st, dict):
                stack = sorted({x.strip() for s in st.values() for x in s.split(",") if x.strip()})
            else:
                stack = [x.strip() for x in (st or "").split(",") if x.strip()]
            links = p.get("links", {}) or {}
            shot_file = pathlib.Path(__file__).resolve().parents[1] / "public" / "shots" / f"{slug}.jpg"
            rows.append({
                "slug": slug, "domain": did,
                "name": p.get("name", slug), "tagline": p.get("tagline", ""),
                "note": p.get("note", ""), "stack": stack,
                "live": links.get("live", ""), "code": links.get("code", ""),
                # the query is a hash of the shots, so replacing one changes its URL
                # and no browser or optimizer cache can keep serving the old image
                "shot": f"/shots/{slug}.jpg?v={version}" if shot_file.exists() else "",
                "highlights": bullets[:6],
            })

    body = ["// GENERATED by tools/build-content.ts.py from ../resume-build/profile.json",
            "// Do not edit by hand. Change profile.json and rerun, so the site and the resumes agree.",
            "",
            "export type Project = {",
            "  slug: string; domain: string; name: string; tagline: string; note: string;",
            "  stack: string[]; live: string; code: string; shot: string; highlights: string[];",
            "};", "",
            "export const DOMAINS = ["]
    for did, dtitle, dblurb, _ in DOMAINS:
        body.append(f"  {{ id: `{esc(did)}`, title: `{esc(dtitle)}`, blurb: `{esc(dblurb)}` }},")
    body += ["] as const;", "", "export const PROJECTS: Project[] = ["]
    for r in rows:
        body.append("  {")
        for k in ("slug", "domain", "name", "tagline", "note", "live", "code", "shot"):
            body.append(f"    {k}: `{esc(str(r[k]))}`,")
        body.append("    stack: [" + ", ".join(f"`{esc(s)}`" for s in r["stack"]) + "],")
        body.append("    highlights: [")
        for h in r["highlights"]:
            body.append(f"      `{esc(h)}`,")
        body.append("    ],")
        body.append("  },")
    body += ["];", ""]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(body))
    print(f"wrote {OUT.relative_to(OUT.parents[2])}: {len(rows)} projects across {len(DOMAINS)} domains")
    if missing:
        print("  in profile.json but not placed in a domain:", ", ".join(missing))
    if extra:
        print("  listed in a domain but absent from profile.json:", ", ".join(extra))

if __name__ == "__main__":
    main()
