"""Sync the built resumes into the site and regenerate their index.

The PDFs are built in ../resume-build and written to ../Ideal Resumes. The site
serves copies from public/resume, and those copies had drifted: all fourteen
were older than the builds. Run this after every resume rebuild.

  python3 tools/build-resumes.py
"""
import pathlib, shutil

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT.parent / "Ideal Resumes"
DST = ROOT / "public" / "resume"
OUT = ROOT / "src" / "content" / "resumes.generated.ts"

# grouping for the picker, by the kind of team hiring
GROUP = {
    "AI Engineer": "AI and agents", "Agentic AI Engineer": "AI and agents",
    "Generative AI Engineer": "AI and agents", "AI Product Engineer": "AI and agents",
    "Machine Learning Engineer": "Machine learning", "Deep Learning Engineer": "Machine learning",
    "Applied ML and Deep Learning Engineer": "Machine learning", "Data Scientist": "Machine learning",
    "Software Engineer": "Engineering", "DevOps and Platform Engineer": "Engineering",
    "Product Manager": "Product and analytics", "AI Product Manager": "Product and analytics",
    "Data Analyst": "Product and analytics", "Business Analyst": "Product and analytics",
}

DST.mkdir(parents=True, exist_ok=True)
pdfs = sorted(SRC.glob("Adarsh_Dwivedi_*.pdf"))
for old in DST.glob("*.pdf"):
    if not (SRC / old.name).exists():
        old.unlink()
rows = []
for f in pdfs:
    shutil.copy2(f, DST / f.name)
    label = f.stem.removeprefix("Adarsh_Dwivedi_").replace("_", " ")
    rows.append((label, f.name, round(f.stat().st_size / 1024), GROUP.get(label, "Engineering")))

esc = lambda s: s.replace('"', '\\"')
lines = [
    "// GENERATED by tools/build-resumes.py from ../Ideal Resumes. One PDF per target role.",
    "export type Resume = { label: string; file: string; kb: number; group: string };",
    "export const RESUMES: Resume[] = [",
    *[f'  {{ label: "{esc(l)}", file: "{esc(n)}", kb: {k}, group: "{esc(g)}" }},' for l, n, k, g in rows],
    "];",
    "",
]
OUT.write_text("\n".join(lines))
print(f"synced {len(rows)} resumes into public/resume")
